### ISSUE TITLE
Elasticstat KeyError: 'http'

### ISSUE THREAD

**Issue by ricard0ff** [objectrocket/elasticstat#10]
So after trying the version via pip 1.2.0 I ran into issue #8, so I downloaded the latest 1.3.0 and installed it, but this is the error I'm getting when I run it:

```
rferreira@elastic1-cab1:~/elasticstat-master$ elasticstat -h 172.24.9.71
cluster                           status   shards  pri relo init unassign   pending tasks   time
elastic-graylog                   green       110   55    0    0        0               0   10:51:25
nodes                    role                   load  mem   heap  old sz   old gc   young gc   index    search   bulk     get        fde|fdt    hconn  tconn     merges   idx st       disk usage  docs
elastic2-cab2.localnet   ALL*                   0.01  93%    13%  3.3gb    -|-      -|-        0|0|0    0|0|0    0|0|0    0|0|0        -|-        0|-     65      17.9h       0s     125.70 GB|2%  255106228
elastic1-cab2.localnet   ALL                    0.39  97%    19%  5.2gb    -|-      -|-        0|0|0    0|0|0    0|0|0    0|0|0        -|-        0|-     65      18.5h       0s     129.80 GB|2%  254607932
elastic1-cab1.localnet   ALL                    0.16  97%    66%  19.2gb   -|-      -|-        0|0|0    0|0|0    0|0|0    0|0|0        -|-        1|-     65      19.1h       0s     147.07 GB|2%  259062831
elastic2-cab1.localnet   ALL                    0.37  93%    51%  14gb     -|-      -|-        0|0|0    0|0|0    0|0|0    0|0|0        -|-        0|-     65      19.6h       0s     127.54 GB|2%  261213741
Traceback (most recent call last):
  File "/usr/local/bin/elasticstat", line 9, in <module>
    load_entry_point('elasticstat==1.3.0', 'console_scripts', 'elasticstat')()
  File "build/bdist.linux-x86_64/egg/elasticstat/elasticstat.py", line 561, in main
  File "build/bdist.linux-x86_64/egg/elasticstat/elasticstat.py", line 489, in print_stats
  File "build/bdist.linux-x86_64/egg/elasticstat/elasticstat.py", line 417, in process_role
  File "build/bdist.linux-x86_64/egg/elasticstat/elasticstat.py", line 387, in process_node
  File "build/bdist.linux-x86_64/egg/elasticstat/elasticstat.py", line 359, in process_node_connections
KeyError: 'http'
```

iterating trough the node keys shows that some nodes don't have that key:
```
thread_pool
transport_address
name
script
process
timestamp
breakers
host
fs
jvm
ip
indices
attributes
os
transport
```

I've made this dirty patch:
```
    def process_node_connections(self, role, node_id, node):
        processed_node_conns = {}
        if node.get('http') == None:
                node['http'] = {u'total_opened': 0, u'current_open': 0}
        processed_node_conns['http_conn'] = self.get_http_conns(node_id, node['http'])
        processed_node_conns['transport_conn'] = node['transport']['server_open']
        return(NODES_TEMPLATE['connections'].format(**processed_node_conns))
```
do you think a PR is in order?

thanks
Ricardo

**Comment by jtharpla** [comment]
@ricard0ff Ah!  When I wrote elasticstat, I was working entirely with clusters where all nodes had http connections enabled.  It looks like you have explicitly disabled http on some nodes.  Your suggested fix looks good to me, would you like to submit this as a PR?

Out of curiosity, what version of elasticsearch are you running?

**Comment by ricard0ff** [comment]
@jtharpla thanks for getting back, submitted a PR.
I'm running version 2.3.2, why?

**Comment by evanfreed** [comment]
Awesome, thanks for the feedback! Will review the PR and merge.
