### ISSUE TITLE
ES 5 - Load Average Change

### ISSUE THREAD

**Issue by evanfreed** [objectrocket/elasticstat#12]
https://www.elastic.co/guide/en/elasticsearch/reference/5.x/breaking_50_index_apis.html

```
Traceback (most recent call last):
  File "/usr/local/bin/elasticstat", line 11, in <module>
    sys.exit(main())
  File "/root/.virtualenvs/elasticstat/lib/python2.7/site-packages/elasticstat/elasticstat.py", line 501, in main
    elasticstat.print_stats()
  File "/root/.virtualenvs/elasticstat/lib/python2.7/site-packages/elasticstat/elasticstat.py", line 434, in print_stats
    self.process_role(role, nodes_stats)
  File "/root/.virtualenvs/elasticstat/lib/python2.7/site-packages/elasticstat/elasticstat.py", line 369, in process_role
    row = self.process_node(current_role, node_id, nodes_stats['nodes'][node_id])
  File "/root/.virtualenvs/elasticstat/lib/python2.7/site-packages/elasticstat/elasticstat.py", line 340, in process_node
    node_segments.append(category_func(role, node_id, node))
  File "/root/.virtualenvs/elasticstat/lib/python2.7/site-packages/elasticstat/elasticstat.py", line 274, in process_node_os
    node_load_avg = node['os']['load_average']
KeyError: 'load_average'
```

**Comment by evanfreed** [comment]
Closing, was using an older version of elasticstat

**Comment by danielmotaleite** [comment]
Hi
i'm also seeing this, but i have installed the latest version from pip

where did you installed a more updated version?
