### ISSUE TITLE
elasticstat crashes with KeyError: 'attributes'

### ISSUE THREAD

**Issue by arne-cl** [objectrocket/elasticstat#18]
This happens when I run this against a local two-node cluster of Elasticsearch 6.1.3:

```$ elasticstat
cluster                           status   shards  pri relo init unassign   pending tasks   time    
docker-cluster                    yellow       40   35    0    0       30               0   20:09:58
Traceback (most recent call last):
  File "/usr/bin/elasticstat", line 11, in <module>
    load_entry_point('elasticstat==1.2.0', 'console_scripts', 'elasticstat')()
  File "/usr/lib/python2.7/site-packages/elasticstat/elasticstat.py", line 501, in main
    elasticstat.print_stats()
  File "/usr/lib/python2.7/site-packages/elasticstat/elasticstat.py", line 418, in print_stats
    node_role = self.get_role(nodes_stats['nodes'][node_id]['attributes'])
KeyError: 'attributes'
```

**Comment by envyes** [comment]
Is there any work around for this? I am getting this error as well.

**Comment by envyes** [comment]
Looks like the latest code takes care of this error but is not included in any release and has not been uploaded to the package manager. Any plans of doing it soon?

**Comment by paulrossmeier** [comment]
This indeed has been fixed and will be looking to upload the latest version to pypi soon

Paul Rossmeier
